In [2]:
#Data structures,functions ,numpy & pandas

# Section A: Data Structures & Control Structures
# 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [5]:
# 1. Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

# Create a list of 5 integers
my_list = [10, 20, 30, 40, 50]
print(f"Original list: {my_list}")

# append: Add an element to the end of the list
my_list.append(60)
print(f"After append(60): {my_list}")

# extend: Add elements of an iterable (e.g., another list) to the end of the list
my_list.extend([70, 80])
print(f"After extend([70, 80]): {my_list}")

# insert: Add an element at a specific index
my_list.insert(1, 15)
print(f"After insert(1, 15): {my_list}")

# remove: Remove the first occurrence of a specified value
my_list.remove(30)
print(f"After remove(30): {my_list}")

# pop: Remove and return the element at a specified index (or the last element if no index is given)
popped_element = my_list.pop(0) # Remove element at index 0
print(f"After pop(0): {my_list}, Popped element: {popped_element}")

# index: Return the index of the first occurrence of a specified value
index_of_40 = my_list.index(40)
print(f"Index of 40: {index_of_40}")

# count: Return the number of times a specified value appears in the list
my_list.append(40) # Add another 40 for demonstration
count_of_40 = my_list.count(40)
print(f"After appending another 40, count of 40: {count_of_40}")

# sort: Sort the list in ascending order (in-place)
my_list.sort()
print(f"After sort(): {my_list}")

# reverse: Reverse the order of elements in the list (in-place)
my_list.reverse()
print(f"After reverse(): {my_list}")

# clear: Remove all elements from the list
my_list.clear()
print(f"After clear(): {my_list}")

Original list: [10, 20, 30, 40, 50]
After append(60): [10, 20, 30, 40, 50, 60]
After extend([70, 80]): [10, 20, 30, 40, 50, 60, 70, 80]
After insert(1, 15): [10, 15, 20, 30, 40, 50, 60, 70, 80]
After remove(30): [10, 15, 20, 40, 50, 60, 70, 80]
After pop(0): [15, 20, 40, 50, 60, 70, 80], Popped element: 10
Index of 40: 2
After appending another 40, count of 40: 2
After sort(): [15, 20, 40, 40, 50, 60, 70, 80]
After reverse(): [80, 70, 60, 50, 40, 40, 20, 15]
After clear(): []


In [39]:
2.#Create a tuple that stores 3 student names. Try changing the second name in the tuple.
 #What happens? Explain why.

 # Create a tuple with 3 student names
students = ("Divya", "Navya", "Ramya")

# Display the original tuple
print("Original tuple:")
print(students)

# Try changing the second name
try:
    students[1] = "David"
except TypeError as e:
    print("\nError:")
    print(e)
# Explain why the error occurred
print("\nExplanation:")
print("A tuple is immutable, which means its elements cannot be changed after it is created.")
print("Therefore, trying to modify an element in a tuple raises a TypeError.")

Original tuple:
('Divya', 'Navya', 'Ramya')

Error:
'tuple' object does not support item assignment

Explanation:
A tuple is immutable, which means its elements cannot be changed after it is created.
Therefore, trying to modify an element in a tuple raises a TypeError.


In [17]:
3.# Program to demonstrate that sets do not allow duplicate values

# Create a set with duplicate integers
numbers = {10, 20, 30, 40, 10, 70, 30, 20}

# Print the set
print("Set elements:")
print(numbers)

# Explain the output
print("\nExplanation:")
print("A set stores only unique values.")
print("Duplicate values are automatically removed.")
print("Therefore, each number appears only once in the output.")

Set elements:
{20, 70, 40, 10, 30}

Explanation:
A set stores only unique values.
Duplicate values are automatically removed.
Therefore, each number appears only once in the output.


In [23]:
4.# Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.# Create a dictionary
person = {
    "name": "Vasavi",
    "age": 24,
    "city": "Hyderabad"
}

# Update the age
person["age"] = 21

# Add a new key 'email'
person["email"] = "vasavi@example.com"

# Print the final dictionary
print(person)

{'name': 'Vasavi', 'age': 21, 'city': 'Hyderabad', 'email': 'vasavi@example.com'}


In [26]:
5. #Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.
# Take age as a variable
age = 16

# Check eligibility
if age >= 14:
    print("Eligible to vote.")
else:
    print("Not eligible to vote.")

Eligible to vote.


In [29]:
6.# Given a 'marks' variable, print the grade: - 90 and above: 'A' - 75–89: 'B' - 50–74: 'C' - Below 50: 'Fail'
# Given marks
marks = 82

# Check grade
if marks >= 90:
    print("Grade: A")
elif marks >= 60:
    print("Grade: B")
elif marks >= 40:
    print("Grade: C")
else:
    print("Grade: Fail")

Grade: B


In [30]:
7.# Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.
# Given number
num = 6

# Check the number
if num > 0:
    print("The number is positive.")
    if num % 2 == 0:
        print("The number is even.")
    else:
        print("The number is odd.")
elif num == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

The number is positive.
The number is even.


In [31]:
#Section B: Numpy

8.# Create: - A scalar using np.array(5) - A 1D array with values 1 to 5 - A 2D array (2x3) with values from 10 to 60 in steps of 10
import numpy as np

# Create a scalar
scalar = np.array(5)

# Create a 1D array with values 1 to 5
array_1d = np.array([1, 2, 3, 4, 5])

# Create a 2D array (2x3) with values from 10 to 60 in steps of 10
array_2d = np.array([[10, 20, 30],
                     [40, 50, 60]])

# Print the arrays
print("Scalar:")
print(scalar)

print("\n1D Array:")
print(array_1d)

print("\n2D Array:")
print(array_2d)

Scalar:
5

1D Array:
[1 2 3 4 5]

2D Array:
[[10 20 30]
 [40 50 60]]


In [37]:
9.# Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().
import numpy as np

import numpy as np

# Generate a 4x4 array of random integers between 0 and 100
random_array = np.random.randint(0, 101, size=(4, 4))

# Print the array
print(random_array)

[[23 18 95  1]
 [98 92 47 51]
 [63 29 82 41]
 [45 44 64 25]]


In [38]:
10. #Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'
import numpy as np
import pandas as pd

# Create a 3x3 NumPy array
array = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Convert to a Pandas DataFrame
df = pd.DataFrame(array, columns=['A', 'B', 'C'])

# Print the DataFrame
print(df)

    A   B   C
0  10  20  30
1  40  50  60
2  70  80  90
